### ISSUE TITLE
containers can;t communicate

### ISSUE THREAD

**Issue by wolfman2g1** [RafPe/docker-phpipam#2]
phpipam doesn;t pre populate all of the ENV. 

when filled in manually. I get the following error

Could not connect to database! SQLSTATE[HY000] [1130] Host '172.21.0.3' is not allowed to connect to this MariaDB server

**Comment by RafPe** [comment]
Hey @wolfman2g1 

I spinned up the environment using docker compose and I can without any problems create database. 

Do you tick box to drop database if already exists ? How does your variable looks like ? 

![alt text](https://s3.eu-central-1.amazonaws.com/raftech-s3/docker_phpipam.png)

**Comment by wolfman2g1** [comment]
I was able to get it working. the issue was which user i was trying to connect to the database with. wasn't clear that i needed yo use root, had to re-read the mariadb docker, reference.

**Comment by RafPe** [comment]
You could of course change the default user and db with specific options when creating mariadb container.
